stages:
  data_preparation:
    cmd: python src/EmotionRecognition/pipeline/stage_01_data_preparation.py
    deps:
      - src/EmotionRecognition/pipeline/stage_01_data_preparation.py
      - src/EmotionRecognition/components/data_preparation.py
      - data/raw/fer2013.csv
      - data/raw/fer2013new.csv
      - data/raw/CK+48
    params:
      - DATA_PARAMS.CLASSES
    outs:
      - artifacts/data_preparation/train
      - artifacts/data_preparation/test

  model_training:
    cmd: python src/EmotionRecognition/pipeline/stage_02_model_training.py
    deps:
      - src/EmotionRecognition/pipeline/stage_02_model_training.py
      - src/EmotionRecognition/components/model_trainer.py
      - artifacts/data_preparation/train
      - artifacts/data_preparation/test
    params:
      - DATA_PARAMS
      - TRAINING_PARAMS
    outs:
      - artifacts/training/model.keras

  model_evaluation:
    cmd: python src/EmotionRecognition/pipeline/stage_03_model_evaluation.py
    deps:
      - src/EmotionRecognition/components/model_evaluation.py
      - artifacts/data_preparation/test
      - artifacts/training/model.keras
    params:
      - DATA_PARAMS
    metrics:
      - artifacts/evaluation/metrics.json:
          cache: false