# Data Preprocessing Parameters
DATA_PARAMS:
  IMAGE_SIZE: [224, 224]       # Standard size for EfficientNet-B0 input
  CHANNELS: 3                  # We will convert grayscale images to 3 channels (RGB)
  BATCH_SIZE: 32               # Standard batch size
  
  # The 7 emotion classes based on your analysis
  CLASSES: ['angry', 'disgust', 'fear', 'happy', 'neutral', 'sad', 'surprise']
  NUM_CLASSES: 7
  
  # Class Weights based on your analysis (Manually set to start)
  # This is CRITICAL for addressing the imbalance. 
  # We will calculate these more precisely in the preprocessing step, but use ratios for placeholders.
  # (Disgust is the lowest, Happy is the highest)
  CLASS_WEIGHTS:
    0: 1.5   # Angry (slightly higher weight)
    1: 6.0   # Disgust (HIGH weight to penalize errors heavily)
    2: 1.5   # Fear (slightly higher weight)
    3: 0.5   # Happy (LOW weight to de-emphasize this dominant class)
    4: 1.0   # Neutral (Base weight)
    5: 1.0   # Sad (Base weight)
    6: 1.5   # Surprise (slightly higher weight)

# Model Training Parameters (EfficientNet-B0)
TRAINING_PARAMS:
  EPOCHS: 50
  LEARNING_RATE: 0.001
  OPTIMIZER: Adam
  LOSS_FUNCTION: CategoricalCrossentropy
  METRICS: ['accuracy']
  DROPOUT_RATE: 0.2          # Regularization
  
# Model Evaluation Parameters
EVALUATION_PARAMS:
  METRIC_THRESHOLD: 0.65     # Minimum overall accuracy required to register model