DATA_PARAMS:
  IMAGE_SIZE: [224, 224]
  CHANNELS: 3
  BATCH_SIZE: 32
  # Our final 7 classes (Contempt is merged into Disgust)
  CLASSES: ['angry', 'disgust', 'fear', 'happy', 'neutral', 'sad', 'surprise']
  NUM_CLASSES: 7

TRAINING_PARAMS:
  EPOCHS: 50 # A solid number for a baseline run
  LEARNING_RATE: 0.0001 # A small, stable learning rate
  OPTIMIZER: Adam
  LOSS_FUNCTION: CategoricalCrossentropy
  METRICS: ['accuracy']
  DROPOUT_RATE: 0.5 # Strong regularization is good