DATA_PARAMS:
  IMAGE_SIZE: [224, 224]
  CHANNELS: 3
  BATCH_SIZE: 32
  CLASSES: ['anger', 'contempt', 'disgust', 'fear', 'happy', 'sadness', 'surprise']
  NUM_CLASSES: 7
  VALIDATION_SPLIT: 0.2


TRAINING_PARAMS:
  EPOCHS: 50
  LEARNING_RATE: 0.001 # A stable LR for training a simple head
  OPTIMIZER: Adam
  LOSS_FUNCTION: CategoricalCrossentropy
  METRICS: ['accuracy']
  DROPOUT_RATE: 0.4