artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_dataset_id: alyyan/emotion-detection  # The ID from Kaggle website
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion          # Where the 'train' and 'test' folders will be

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/EmotionRecognition  # The directory to check
  status_file: artifacts/data_validation/status.txt

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  train_data_dir: artifacts/data_ingestion/EmotionRecognition/train
  test_data_dir: artifacts/data_ingestion/EmotionRecognition/test
  # Paths to save the final processed TensorFlow datasets
  train_dataset_path: artifacts/data_preprocessing/train_dataset
  test_dataset_path: artifacts/data_preprocessing/test_dataset

# Update this section in your config/config.yaml

model_trainer:
  root_dir: artifacts/training
  train_data_dir: artifacts/data_ingestion/EmotionRecognition/train
  test_data_dir: artifacts/data_ingestion/EmotionRecognition/test
  trained_model_path: artifacts/training/model.weights.h5

model_evaluation:
  root_dir: artifacts/evaluation
  metrics_file_name: metrics.json