artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_dataset_id: shawon10/ckplus
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/CK+ 
  status_file: artifacts/data_validation/status.txt

model_trainer:
  root_dir: artifacts/training
  data_dir: artifacts/data_ingestion/CK+
  trained_model_path: artifacts/training/model.keras

model_evaluation:
  root_dir: artifacts/evaluation
  data_dir: artifacts/data_ingestion/CK+
  trained_model_path: artifacts/training/model.keras
  metrics_file_name: artifacts/evaluation/metrics.json
  mlflow_uri: https://dagshub.com/AlyyanAhmed21/Emotion-Recognition-MLOps.mlflow