artifacts_root: artifacts

data_preparation: # This is our Stage 1
  root_dir: artifacts/data_preparation
  # Inputs from raw data
  ferplus_pixels_csv: data/raw/fer2013.csv
  ferplus_labels_csv: data/raw/fer2013new.csv
  ckplus_dir: data/raw/CK+48
  # Outputs
  combined_train_dir: artifacts/data_preparation/train
  ferplus_test_dir: artifacts/data_preparation/test

model_trainer:
  root_dir: artifacts/training
  # The trainer now takes its input directly from the preparation stage
  train_data_dir: artifacts/data_preparation/train
  test_data_dir: artifacts/data_preparation/test
  trained_model_path: artifacts/training/model.keras

model_evaluation:
  root_dir: artifacts/evaluation
  test_data_dir: artifacts/data_preparation/test
  trained_model_path: artifacts/training/model.keras
  metrics_file_name: artifacts/evaluation/metrics.json
  mlflow_uri: https://dagshub.com/AlyyanAhmed21/Emotion-Recognition-MLOps.mlflow # Example for DagsHub