artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_dataset_id: alyyan/emotion-detection  # The ID from Kaggle website
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion          # Where the 'train' and 'test' folders will be

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  train_data_path: artifacts/data_preprocessing/train_processed
  test_data_path: artifacts/data_preprocessing/test_processed

model_trainer:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

model_evaluation:
  root_dir: artifacts/evaluation
  metrics_file_name: metrics.json